import type { Trip } from './types'

export const sampleTrip: Trip = {
  id: 'anime-expo-2026',
  title: 'Anime Expo 2026',
  subtitle: 'Los Angeles ops plan',
  dates: {
    start: '2026-07-03',
    end: '2026-07-05',
  },
  base: {
    hotel: 'Holiday Inn Diamond Bar - Pomona',
    car: 'Hertz LAX pickup, ONT dropoff',
    timezone: 'America/Los_Angeles',
  },
  updatedAt: new Date('2026-06-02T21:00:00.000Z').toISOString(),
  items: [
    {
      id: 'arrive-lax',
      date: '2026-07-03',
      time: '08:53',
      title: 'Arrive at LAX',
      category: 'flight',
      location: 'Los Angeles International Airport',
      address: '1 World Way, Los Angeles, CA',
      durationMinutes: 80,
      status: 'locked',
      priority: 'high',
      confirmation: 'B6 flight confirmation',
      leaveBy: '10:20',
      notes: [
        'Use restroom and refill water before rental shuttle.',
        'If the rental counter line is slow, skip the food stop and go directly downtown.',
      ],
      links: [
        {
          label: 'Airport map',
          url: 'https://www.flylax.com/',
        },
      ],
    },
    {
      id: 'hertz-lax',
      date: '2026-07-03',
      time: '10:10',
      title: 'Pick up rental car',
      category: 'errand',
      location: 'Hertz LAX',
      address: '9000 Airport Blvd, Los Angeles, CA',
      durationMinutes: 35,
      status: 'planned',
      priority: 'high',
      confirmation: 'Hertz reservation',
      notes: [
        'Inspect wheels, bumpers, windshield, and fuel level before leaving the lot.',
        'Pair phone and start navigation before entering traffic.',
      ],
      links: [
        {
          label: 'Navigate',
          url: 'https://www.google.com/maps/search/?api=1&query=Hertz+LAX',
        },
      ],
    },
    {
      id: 'in-n-out',
      date: '2026-07-03',
      time: '10:55',
      title: 'In-N-Out LAX',
      category: 'food',
      location: 'In-N-Out Burger',
      address: '9149 S Sepulveda Blvd, Los Angeles, CA',
      durationMinutes: 35,
      status: 'planned',
      priority: 'medium',
      costEstimate: 18,
      leaveBy: '11:35',
      notes: [
        'Use this as a traffic buffer, not a hard commitment.',
        'Plane photo stop only if the line is short.',
      ],
      parking: {
        primary: 'Small restaurant lot',
        backup: 'Skip stop if lot is gridlocked',
        warning: 'Do not leave luggage visible in the car.',
      },
      links: [
        {
          label: 'Google Maps',
          url: 'https://www.google.com/maps/search/?api=1&query=9149+S+Sepulveda+Blvd+Los+Angeles',
        },
      ],
    },
    {
      id: 'anime-expo-day-1',
      date: '2026-07-03',
      time: '12:30',
      title: 'Anime Expo arrival',
      category: 'event',
      location: 'Los Angeles Convention Center',
      address: '1201 S Figueroa St, Los Angeles, CA',
      durationMinutes: 300,
      status: 'planned',
      priority: 'high',
      costEstimate: 45,
      leaveBy: '17:40',
      notes: [
        'Screenshot badge, QR codes, and hotel address before entering.',
        'Set a phone alarm for the hotel commute cutoff.',
        'Keep one sealed water bottle and battery pack accessible.',
      ],
      parking: {
        primary: 'LACC West Hall Garage',
        backup: 'LA Live parking, then walk over',
        warning: 'Hide bags in trunk before reaching the parking area.',
      },
      links: [
        {
          label: 'Venue',
          url: 'https://www.anime-expo.org/',
        },
        {
          label: 'Navigate',
          url: 'https://www.google.com/maps/search/?api=1&query=Los+Angeles+Convention+Center',
        },
      ],
    },
    {
      id: 'hotel-checkin',
      date: '2026-07-03',
      time: '19:00',
      title: 'Hotel check-in',
      category: 'hotel',
      location: 'Holiday Inn Diamond Bar - Pomona',
      address: '21725 Gateway Center Dr, Diamond Bar, CA',
      durationMinutes: 45,
      status: 'locked',
      priority: 'high',
      confirmation: 'Hotel confirmation',
      notes: [
        'Ask about late checkout and breakfast hours.',
        'Refill cooler and stage AX bag for the next morning.',
      ],
      parking: {
        primary: 'Hotel lot',
        backup: 'Front desk overflow guidance',
      },
      links: [
        {
          label: 'Navigate',
          url: 'https://www.google.com/maps/search/?api=1&query=Holiday+Inn+Diamond+Bar+Pomona',
        },
      ],
    },
    {
      id: 'ax-day-2-drive',
      date: '2026-07-04',
      time: '07:45',
      title: 'Drive to AX',
      category: 'drive',
      location: 'Hotel to LACC',
      address: 'Diamond Bar to 1201 S Figueroa St',
      durationMinutes: 55,
      status: 'planned',
      priority: 'high',
      leaveBy: '07:45',
      notes: [
        'Check live traffic before loading the car.',
        'Put hotel key, badge, and parking plan in the same pocket.',
      ],
      links: [
        {
          label: 'Route',
          url: 'https://www.google.com/maps/dir/?api=1&origin=Holiday+Inn+Diamond+Bar+Pomona&destination=Los+Angeles+Convention+Center',
        },
      ],
    },
    {
      id: 'ax-day-2',
      date: '2026-07-04',
      time: '09:15',
      title: 'Anime Expo full day',
      category: 'event',
      location: 'Los Angeles Convention Center',
      address: '1201 S Figueroa St, Los Angeles, CA',
      durationMinutes: 520,
      status: 'planned',
      priority: 'high',
      costEstimate: 55,
      leaveBy: '18:30',
      notes: [
        'Pick one must-see panel and one flexible backup.',
        'Lunch early to avoid peak food lines.',
        'Take receipts/photos for any merch warranty issues.',
      ],
      parking: {
        primary: 'Prepaid LACC parking if available',
        backup: 'Union Station garage + Metro A/E transfer',
        warning: 'Avoid street parking with luggage or merch visible.',
      },
      links: [
        {
          label: 'Navigate',
          url: 'https://www.google.com/maps/search/?api=1&query=Los+Angeles+Convention+Center',
        },
      ],
    },
    {
      id: 'checkout',
      date: '2026-07-05',
      time: '09:30',
      title: 'Checkout and pack car',
      category: 'hotel',
      location: 'Holiday Inn Diamond Bar - Pomona',
      address: '21725 Gateway Center Dr, Diamond Bar, CA',
      durationMinutes: 40,
      status: 'planned',
      priority: 'high',
      leaveBy: '10:15',
      notes: [
        'Photograph room before leaving.',
        'Confirm no chargers, badge, or merch left behind.',
      ],
      parking: {
        primary: 'Hotel lot',
        backup: 'Front desk temporary loading area',
      },
      links: [],
    },
    {
      id: 'return-car-ont',
      date: '2026-07-05',
      time: '12:20',
      title: 'Return rental car',
      category: 'errand',
      location: 'Ontario International Airport Hertz',
      address: '3450 E Airport Dr, Ontario, CA',
      durationMinutes: 35,
      status: 'planned',
      priority: 'high',
      confirmation: 'Hertz return',
      notes: [
        'Fill gas within 10 miles of the airport.',
        'Keep final receipt screenshot before security.',
      ],
      links: [
        {
          label: 'Navigate',
          url: 'https://www.google.com/maps/search/?api=1&query=Ontario+Airport+Hertz',
        },
      ],
    },
  ],
  checklists: [
    {
      id: 'daily-carry',
      title: 'Daily carry',
      items: [
        { id: 'badge', label: 'AX badge and ID', checked: false },
        { id: 'battery', label: 'Battery pack and cable', checked: false },
        { id: 'water', label: 'Water bottle', checked: false },
        { id: 'earbuds', label: 'Earbuds', checked: false },
      ],
    },
    {
      id: 'parking',
      title: 'Parking before arrival',
      items: [
        { id: 'hide-bags', label: 'Hide bags before reaching destination', checked: false },
        { id: 'screenshot', label: 'Screenshot garage QR or receipt', checked: false },
        { id: 'pin-car', label: 'Pin exact car location', checked: false },
      ],
    },
    {
      id: 'checkout',
      title: 'Checkout',
      items: [
        { id: 'chargers', label: 'Chargers and adapters packed', checked: false },
        { id: 'bathroom', label: 'Bathroom counter cleared', checked: false },
        { id: 'receipt', label: 'Hotel receipt saved', checked: false },
      ],
    },
  ],
  documents: [
    {
      id: 'hotel-confirmation',
      title: 'Hotel confirmation',
      type: 'pdf',
      location: 'docs/hotel.pdf',
      note: 'Upload or link the final confirmation before departure.',
    },
    {
      id: 'rental-car',
      title: 'Rental car reservation',
      type: 'pdf',
      location: 'docs/rental-car.pdf',
      note: 'Keep pickup and return confirmation together.',
    },
    {
      id: 'badge-qr',
      title: 'Badge QR screenshot',
      type: 'image',
      location: 'Photos / pinned album',
      note: 'Save offline before entering the venue.',
    },
  ],
}
