import type { Trip } from "./types";

export const tripData: Trip = {
  id: "anime-expo-2026",
  title: "Anime Expo 2026",
  subtitle: "Los Angeles 行程",
  dates: {
    start: "2026-07-03",
    end: "2026-07-05",
  },
  base: {
    hotel: "Holiday Inn Diamond Bar - Pomona",
    car: "Hertz LAX 取车，ONT 还车",
    timezone: "America/Los_Angeles",
  },
  updatedAt: new Date("2026-06-02T21:00:00.000Z").toISOString(),
  items: [
    {
      id: "arrive-lax",
      date: "2026-07-03",
      time: "08:53",
      title: "抵达 LAX",
      category: "flight",
      location: "Los Angeles International Airport",
      address: "1 World Way, Los Angeles, CA",
      durationMinutes: 80,
      status: "locked",
      priority: "high",
      confirmation: "B6 flight confirmation",
      leaveBy: "10:20",
      notes: [
        "搭租车接驳车前先上洗手间并补水。",
        "如果租车柜台排队太慢，跳过用餐点直接去 downtown。",
      ],
      links: [
        {
          label: "机场地图",
          url: "https://www.flylax.com/",
        },
      ],
    },
    {
      id: "hertz-lax",
      date: "2026-07-03",
      time: "10:10",
      title: "取租车",
      category: "errand",
      location: "Hertz LAX",
      address: "9000 Airport Blvd, Los Angeles, CA",
      durationMinutes: 35,
      status: "planned",
      priority: "high",
      confirmation: "Hertz reservation",
      notes: ["离开停车场前检查轮胎、保险杠、挡风玻璃和油量。", "上路前连接手机并开启导航。"],
      links: [
        {
          label: "导航",
          url: "https://www.google.com/maps/search/?api=1&query=Hertz+LAX",
        },
      ],
    },
    {
      id: "in-n-out",
      date: "2026-07-03",
      time: "10:55",
      title: "In-N-Out LAX",
      category: "food",
      location: "In-N-Out Burger",
      address: "9149 S Sepulveda Blvd, Los Angeles, CA",
      durationMinutes: 35,
      status: "planned",
      priority: "medium",
      costEstimate: 18,
      leaveBy: "11:35",
      notes: ["把这里当交通缓冲，不当硬性安排。", "只有排队短的时候才停下来拍飞机。"],
      parking: {
        primary: "餐厅小停车场",
        backup: "如果停车场堵死就跳过",
        warning: "不要把行李露在车里。",
      },
      links: [
        {
          label: "Google Maps",
          url: "https://www.google.com/maps/search/?api=1&query=9149+S+Sepulveda+Blvd+Los+Angeles",
        },
      ],
    },
    {
      id: "anime-expo-day-1",
      date: "2026-07-03",
      time: "12:30",
      title: "Anime Expo 抵达",
      category: "event",
      location: "Los Angeles Convention Center",
      address: "1201 S Figueroa St, Los Angeles, CA",
      durationMinutes: 300,
      status: "planned",
      priority: "high",
      costEstimate: 45,
      leaveBy: "17:40",
      notes: [
        "入场前截图 badge、QR code 和酒店地址。",
        "为去酒店的最晚离场时间设置手机闹钟。",
        "保留一瓶未开封的水和可随手拿到的充电宝。",
      ],
      parking: {
        primary: "LACC West Hall Garage",
        backup: "LA Live 停车后步行过去",
        warning: "到停车区域前先把包藏进后备箱。",
      },
      links: [
        {
          label: "会场",
          url: "https://www.anime-expo.org/",
        },
        {
          label: "导航",
          url: "https://www.google.com/maps/search/?api=1&query=Los+Angeles+Convention+Center",
        },
      ],
    },
    {
      id: "hotel-checkin",
      date: "2026-07-03",
      time: "19:00",
      title: "酒店入住",
      category: "hotel",
      location: "Holiday Inn Diamond Bar - Pomona",
      address: "21725 Gateway Center Dr, Diamond Bar, CA",
      durationMinutes: 45,
      status: "locked",
      priority: "high",
      confirmation: "Hotel confirmation",
      notes: ["询问延迟退房和早餐时间。", "补好冷藏包，把第二天的 AX 包整理好。"],
      parking: {
        primary: "酒店停车场",
        backup: "向前台询问溢出停车位置",
      },
      links: [
        {
          label: "导航",
          url: "https://www.google.com/maps/search/?api=1&query=Holiday+Inn+Diamond+Bar+Pomona",
        },
      ],
    },
    {
      id: "ax-day-2-drive",
      date: "2026-07-04",
      time: "07:45",
      title: "开车去 AX",
      category: "drive",
      location: "酒店到 LACC",
      address: "Diamond Bar to 1201 S Figueroa St",
      durationMinutes: 55,
      status: "planned",
      priority: "high",
      leaveBy: "07:45",
      notes: ["装车前查看实时交通。", "把酒店房卡、badge 和停车方案放在同一个口袋。"],
      links: [
        {
          label: "路线",
          url: "https://www.google.com/maps/dir/?api=1&origin=Holiday+Inn+Diamond+Bar+Pomona&destination=Los+Angeles+Convention+Center",
        },
      ],
    },
    {
      id: "ax-day-2",
      date: "2026-07-04",
      time: "09:15",
      title: "Anime Expo 全天",
      category: "event",
      location: "Los Angeles Convention Center",
      address: "1201 S Figueroa St, Los Angeles, CA",
      durationMinutes: 520,
      status: "planned",
      priority: "high",
      costEstimate: 55,
      leaveBy: "18:30",
      notes: [
        "选一个必看 panel 和一个灵活备选。",
        "早点吃午饭，避开餐饮高峰。",
        "为 merch 保修问题保留收据 / 照片。",
      ],
      parking: {
        primary: "如果可订，优先预付 LACC 停车",
        backup: "Union Station 车库 + Metro A/E 换乘",
        warning: "车里能看到行李或 merch 时避免街边停车。",
      },
      links: [
        {
          label: "导航",
          url: "https://www.google.com/maps/search/?api=1&query=Los+Angeles+Convention+Center",
        },
      ],
    },
    {
      id: "checkout",
      date: "2026-07-05",
      time: "09:30",
      title: "退房并装车",
      category: "hotel",
      location: "Holiday Inn Diamond Bar - Pomona",
      address: "21725 Gateway Center Dr, Diamond Bar, CA",
      durationMinutes: 40,
      status: "planned",
      priority: "high",
      leaveBy: "10:15",
      notes: ["离开前给房间拍照。", "确认没有遗漏充电器、badge 或 merch。"],
      parking: {
        primary: "酒店停车场",
        backup: "前台临时装车区域",
      },
      links: [],
    },
    {
      id: "return-car-ont",
      date: "2026-07-05",
      time: "12:20",
      title: "归还租车",
      category: "errand",
      location: "Ontario International Airport Hertz",
      address: "3450 E Airport Dr, Ontario, CA",
      durationMinutes: 35,
      status: "planned",
      priority: "high",
      confirmation: "Hertz return",
      notes: ["在机场 10 miles 内加满油。", "过安检前保存最终收据截图。"],
      links: [
        {
          label: "导航",
          url: "https://www.google.com/maps/search/?api=1&query=Ontario+Airport+Hertz",
        },
      ],
    },
  ],
  checklists: [
    {
      id: "daily-carry",
      title: "每日随身",
      items: [
        { id: "badge", label: "AX badge 和 ID", checked: false },
        { id: "battery", label: "充电宝和数据线", checked: false },
        { id: "water", label: "水瓶", checked: false },
        { id: "earbuds", label: "耳机", checked: false },
      ],
    },
    {
      id: "parking",
      title: "到达前停车准备",
      items: [
        { id: "hide-bags", label: "到目的地前藏好包", checked: false },
        { id: "screenshot", label: "截图车库 QR 或收据", checked: false },
        { id: "pin-car", label: "标记准确停车位置", checked: false },
      ],
    },
    {
      id: "checkout",
      title: "退房",
      items: [
        { id: "chargers", label: "充电器和转接头已打包", checked: false },
        { id: "bathroom", label: "浴室台面已清空", checked: false },
        { id: "receipt", label: "Hotel 收据已保存", checked: false },
      ],
    },
  ],
  documents: [
    {
      id: "hotel-confirmation",
      title: "酒店确认单",
      type: "pdf",
      location: "docs/hotel.pdf",
      note: "出发前上传或链接最终确认单。",
    },
    {
      id: "rental-car",
      title: "租车预订单",
      type: "pdf",
      location: "docs/rental-car.pdf",
      note: "把取车和还车确认信息放在一起。",
    },
    {
      id: "badge-qr",
      title: "Badge QR 截图",
      type: "image",
      location: "Photos / pinned album",
      note: "入场前离线保存。",
    },
  ],
};
