import type { Trip } from "./types";

export const tripData: Trip = {
  id: "anime-expo-2026",
  title: "Anime Expo 2026",
  subtitle: "Los Angeles 行程",
  dates: {
    start: "2026-07-03",
    end: "2026-07-05",
  },
  base: {
    hotel: "Holiday Inn Diamond Bar - Pomona",
    car: "Hertz LAX 取车，ONT 还车",
    timezone: "America/Los_Angeles",
  },
  updatedAt: new Date("2026-06-04T00:00:00.000Z").toISOString(),
  suggestions: [],
  items: [
    {
      id: "arrive-lax",
      date: "2026-07-03",
      time: "10:20",
      title: "落地 LAX",
      category: "flight",
      location: "Los Angeles International Airport",
      address: "1 World Way, Los Angeles, CA",
      durationMinutes: 40,
      status: "locked",
      priority: "high",
      confirmation: "B6 flight confirmation",
      notes: ["找 President CiRCLE 区"],
      links: [
        {
          label: "机场地图",
          url: "https://www.flylax.com/",
        },
      ],
    },
    {
      id: "hertz-lax",
      date: "2026-07-03",
      time: "11:00",
      title: "出机场 · 取租车",
      category: "errand",
      location: "Hertz LAX",
      address: "9000 Airport Blvd, Los Angeles, CA",
      durationMinutes: 30,
      status: "planned",
      priority: "high",
      confirmation: "Hertz reservation",
      notes: ["检查轮胎、保险杠、挡风玻璃和油量"],
      links: [
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Hertz+LAX",
        },
      ],
    },
    {
      id: "in-n-out",
      date: "2026-07-03",
      time: "11:30",
      title: "In-N-Out LAX",
      category: "food",
      location: "In-N-Out Burger",
      address: "9149 S Sepulveda Blvd, Los Angeles, CA",
      durationMinutes: 30,
      status: "planned",
      priority: "medium",
      costEstimate: 18,
      notes: ["拍飞机。"],
      links: [
        {
          label: "Google Maps",
          url: "https://maps.apple.com/?q=9149+S+Sepulveda+Blvd+Los+Angeles",
        },
      ],
    },
    {
      id: "anime-expo-day-1",
      date: "2026-07-03",
      time: "12:00",
      title: "Anime Expo 第一天",
      category: "event",
      location: "Los Angeles Convention Center",
      address: "1201 S Figueroa St, Los Angeles, CA",
      durationMinutes: 360,
      status: "planned",
      priority: "high",
      costEstimate: 45,
      leaveBy: "18:00",
      notes: ["入场前带 badge", "带充电宝"],
      links: [
        {
          label: "会场",
          url: "https://www.anime-expo.org/",
        },
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Los+Angeles+Convention+Center",
        },
      ],
    },
    {
      id: "dinner-fri",
      date: "2026-07-03",
      time: "18:30",
      title: "晚餐（待定）",
      category: "food",
      location: "待定",
      address: "待定",
      durationMinutes: 60,
      status: "planned",
      priority: "low",
      notes: ["地点待定"],
      links: [],
    },
    {
      id: "hotel-checkin",
      date: "2026-07-03",
      time: "21:00",
      title: "回酒店入住",
      category: "hotel",
      location: "Holiday Inn Diamond Bar - Pomona",
      address: "21725 Gateway Center Dr, Diamond Bar, CA",
      durationMinutes: 45,
      status: "locked",
      priority: "high",
      confirmation: "Hotel confirmation",
      notes: ["有早餐吗"],
      parking: {
        primary: "酒店 FREE 停车场",
      },
      links: [
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Holiday+Inn+Diamond+Bar+Pomona",
        },
      ],
    },
    {
      id: "wake-sat",
      date: "2026-07-04",
      time: "08:00",
      title: "起床 · 出发",
      category: "errand",
      location: "Holiday Inn Diamond Bar - Pomona",
      address: "21725 Gateway Center Dr, Diamond Bar, CA",
      durationMinutes: 90,
      status: "planned",
      priority: "medium",
      leaveBy: "08:30",
      notes: ["8:30 前出发，开车约 55 分钟到 LACC。", "带酒店房卡、badge"],
      links: [
        {
          label: "路线",
          url: "https://maps.apple.com/?saddr=Holiday+Inn+Diamond+Bar+Pomona&daddr=Los+Angeles+Convention+Center",
        },
      ],
    },
    {
      id: "ax-day-2",
      date: "2026-07-04",
      time: "09:30",
      title: "Anime Expo 全天",
      category: "event",
      location: "Los Angeles Convention Center",
      address: "1201 S Figueroa St, Los Angeles, CA",
      durationMinutes: 510,
      status: "planned",
      priority: "high",
      costEstimate: 55,
      leaveBy: "18:00",
      notes: [],
      parking: {
        primary: "没定",
      },
      links: [
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Los+Angeles+Convention+Center",
        },
      ],
    },
    {
      id: "dinner-sat",
      date: "2026-07-04",
      time: "18:30",
      title: "晚餐（待定）",
      category: "food",
      location: "待定",
      address: "待定",
      durationMinutes: 60,
      status: "planned",
      priority: "low",
      notes: ["地点待定"],
      links: [],
    },
    {
      id: "attraction-sat",
      date: "2026-07-04",
      time: "19:30",
      title: "景点（待定）",
      category: "event",
      location: "待定",
      address: "待定",
      durationMinutes: 90,
      status: "planned",
      priority: "low",
      notes: ["地点待定"],
      links: [],
    },
    {
      id: "back-hotel-sat",
      date: "2026-07-04",
      time: "21:00",
      title: "回酒店",
      category: "hotel",
      location: "Holiday Inn Diamond Bar - Pomona",
      address: "21725 Gateway Center Dr, Diamond Bar, CA",
      durationMinutes: 30,
      status: "planned",
      priority: "medium",
      notes: [],
      parking: {
        primary: "酒店 FREE 停车场",
      },
      links: [
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Holiday+Inn+Diamond+Bar+Pomona",
        },
      ],
    },
    {
      id: "checkout",
      date: "2026-07-05",
      time: "08:00",
      title: "起床 · 退房装车",
      category: "hotel",
      location: "Holiday Inn Diamond Bar - Pomona",
      address: "21725 Gateway Center Dr, Diamond Bar, CA",
      durationMinutes: 90,
      status: "planned",
      priority: "high",
      notes: ["离开前给房间拍照。", "确认没有遗漏充电器"],
      parking: {
        primary: "酒店停车场",
      },
      links: [],
    },
    {
      id: "attraction-sun",
      date: "2026-07-05",
      time: "09:30",
      title: "景点（待定）",
      category: "event",
      location: "待定",
      address: "待定",
      durationMinutes: 240,
      status: "planned",
      priority: "low",
      notes: ["地点待定", "21:00 前往机场"],
      links: [],
    },
    {
      id: "return-airport",
      date: "2026-07-05",
      time: "21:00",
      title: "回机场（ONT）",
      category: "drive",
      location: "Ontario International Airport",
      address: "2900 E Airport Dr, Ontario, CA",
      durationMinutes: 60,
      status: "planned",
      priority: "high",
      notes: ["还车前在机场 10 miles 内加满油"],
      links: [
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Ontario+International+Airport",
        },
      ],
    },
    {
      id: "return-car-ont",
      date: "2026-07-05",
      time: "22:30",
      title: "归还租车",
      category: "errand",
      location: "Ontario International Airport Hertz",
      address: "3450 E Airport Dr, Ontario, CA",
      durationMinutes: 35,
      status: "planned",
      priority: "high",
      confirmation: "Hertz return",
      notes: ["过安检前保存最终收据截图"],
      links: [
        {
          label: "导航",
          url: "https://maps.apple.com/?q=Ontario+Airport+Hertz",
        },
      ],
    },
    {
      id: "flight-home",
      date: "2026-07-05",
      time: "24:00",
      title: "起飞回程",
      category: "flight",
      location: "Ontario International Airport (ONT)",
      address: "2900 E Airport Dr, Ontario, CA",
      durationMinutes: 90,
      status: "locked",
      priority: "high",
      confirmation: "Return flight confirmation",
      notes: [],
      links: [],
    },
  ],
  checklists: [
    {
      id: "daily-carry",
      title: "每天带",
      items: [
        { id: "badge", label: "AX badge 和 ID", checked: false },
        { id: "battery", label: "充电宝和数据线", checked: false },
        { id: "wallet", label: "钱包", checked: false },
      ],
    },
  ],
  documents: [],
  expenses: [
    {
      id: "flight",
      cat: "transit",
      name: "机票 · JetBlue 往返",
      sub: "JFK ⇄ LAX / ONT · 2 人",
      amount: 993.6,
      credit: 0,
      payer: "xyspg",
    },
    {
      id: "hotel",
      cat: "stay",
      name: "酒店 · Holiday Inn Diamond Bar",
      sub: "2 晚 · 2 Queen Standard",
      amount: 356.62,
      credit: 250,
      payer: "xyspg",
    },
    {
      id: "tickets",
      cat: "event",
      name: "门票 · Anime Expo 2026",
      sub: "2 × 4-Day General Attendee",
      amount: 382.84,
      credit: 0,
      payer: "xyspg",
    },
    {
      id: "car",
      cat: "misc",
      name: "租车 · Hertz",
      sub: "3 天 · Kia K5 或同级",
      amount: 316.6,
      credit: 0,
      payer: "xyspg",
    },
  ],
};
