/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSuggestionsRouteImport } from './routes/admin.suggestions'
import { Route as AdminSplitRouteImport } from './routes/admin.split'
import { Route as AdminItineraryRouteImport } from './routes/admin.itinerary'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuggestionsRoute = AdminSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplitRoute = AdminSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItineraryRoute = AdminItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ledger': typeof LedgerRoute
  '/timeline': typeof TimelineRoute
  '/admin/itinerary': typeof AdminItineraryRoute
  '/admin/split': typeof AdminSplitRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/ledger': typeof LedgerRoute
  '/timeline': typeof TimelineRoute
  '/admin/itinerary': typeof AdminItineraryRoute
  '/admin/split': typeof AdminSplitRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ledger': typeof LedgerRoute
  '/timeline': typeof TimelineRoute
  '/admin/itinerary': typeof AdminItineraryRoute
  '/admin/split': typeof AdminSplitRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/ledger'
    | '/timeline'
    | '/admin/itinerary'
    | '/admin/split'
    | '/admin/suggestions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/ledger'
    | '/timeline'
    | '/admin/itinerary'
    | '/admin/split'
    | '/admin/suggestions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/ledger'
    | '/timeline'
    | '/admin/itinerary'
    | '/admin/split'
    | '/admin/suggestions'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  LedgerRoute: typeof LedgerRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suggestions': {
      id: '/admin/suggestions'
      path: '/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AdminSuggestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/split': {
      id: '/admin/split'
      path: '/split'
      fullPath: '/admin/split'
      preLoaderRoute: typeof AdminSplitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/itinerary': {
      id: '/admin/itinerary'
      path: '/itinerary'
      fullPath: '/admin/itinerary'
      preLoaderRoute: typeof AdminItineraryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminItineraryRoute: typeof AdminItineraryRoute
  AdminSplitRoute: typeof AdminSplitRoute
  AdminSuggestionsRoute: typeof AdminSuggestionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminItineraryRoute: AdminItineraryRoute,
  AdminSplitRoute: AdminSplitRoute,
  AdminSuggestionsRoute: AdminSuggestionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  LedgerRoute: LedgerRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
