/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTripIdRouteImport } from './routes/t.$tripId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as TTripIdIndexRouteImport } from './routes/t.$tripId.index'
import { Route as TTripIdTimelineRouteImport } from './routes/t.$tripId.timeline'
import { Route as TTripIdLedgerRouteImport } from './routes/t.$tripId.ledger'
import { Route as TTripIdBookingsRouteImport } from './routes/t.$tripId.bookings'
import { Route as TTripIdAdminRouteImport } from './routes/t.$tripId.admin'
import { Route as TTripIdAdminIndexRouteImport } from './routes/t.$tripId.admin.index'
import { Route as TTripIdAdminSuggestionsRouteImport } from './routes/t.$tripId.admin.suggestions'
import { Route as TTripIdAdminSplitRouteImport } from './routes/t.$tripId.admin.split'
import { Route as TTripIdAdminSettingsRouteImport } from './routes/t.$tripId.admin.settings'
import { Route as TTripIdAdminMembersRouteImport } from './routes/t.$tripId.admin.members'
import { Route as TTripIdAdminItineraryRouteImport } from './routes/t.$tripId.admin.itinerary'
import { Route as TTripIdAdminBackupsRouteImport } from './routes/t.$tripId.admin.backups'
import { Route as TTripIdAdminAuditRouteImport } from './routes/t.$tripId.admin.audit'
import { Route as TTripIdAdminAgentRouteImport } from './routes/t.$tripId.admin.agent'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTripIdRoute = TTripIdRouteImport.update({
  id: '/t/$tripId',
  path: '/t/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const TTripIdIndexRoute = TTripIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTripIdRoute,
} as any)
const TTripIdTimelineRoute = TTripIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => TTripIdRoute,
} as any)
const TTripIdLedgerRoute = TTripIdLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => TTripIdRoute,
} as any)
const TTripIdBookingsRoute = TTripIdBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => TTripIdRoute,
} as any)
const TTripIdAdminRoute = TTripIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TTripIdRoute,
} as any)
const TTripIdAdminIndexRoute = TTripIdAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminSuggestionsRoute = TTripIdAdminSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminSplitRoute = TTripIdAdminSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminSettingsRoute = TTripIdAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminMembersRoute = TTripIdAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminItineraryRoute = TTripIdAdminItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminBackupsRoute = TTripIdAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminAuditRoute = TTripIdAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => TTripIdAdminRoute,
} as any)
const TTripIdAdminAgentRoute = TTripIdAdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => TTripIdAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ledger': typeof LedgerRoute
  '/timeline': typeof TimelineRoute
  '/admin/$': typeof AdminSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$tripId': typeof TTripIdRouteWithChildren
  '/t/$tripId/admin': typeof TTripIdAdminRouteWithChildren
  '/t/$tripId/bookings': typeof TTripIdBookingsRoute
  '/t/$tripId/ledger': typeof TTripIdLedgerRoute
  '/t/$tripId/timeline': typeof TTripIdTimelineRoute
  '/t/$tripId/': typeof TTripIdIndexRoute
  '/t/$tripId/admin/agent': typeof TTripIdAdminAgentRoute
  '/t/$tripId/admin/audit': typeof TTripIdAdminAuditRoute
  '/t/$tripId/admin/backups': typeof TTripIdAdminBackupsRoute
  '/t/$tripId/admin/itinerary': typeof TTripIdAdminItineraryRoute
  '/t/$tripId/admin/members': typeof TTripIdAdminMembersRoute
  '/t/$tripId/admin/settings': typeof TTripIdAdminSettingsRoute
  '/t/$tripId/admin/split': typeof TTripIdAdminSplitRoute
  '/t/$tripId/admin/suggestions': typeof TTripIdAdminSuggestionsRoute
  '/t/$tripId/admin/': typeof TTripIdAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ledger': typeof LedgerRoute
  '/timeline': typeof TimelineRoute
  '/admin/$': typeof AdminSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$tripId/bookings': typeof TTripIdBookingsRoute
  '/t/$tripId/ledger': typeof TTripIdLedgerRoute
  '/t/$tripId/timeline': typeof TTripIdTimelineRoute
  '/t/$tripId': typeof TTripIdIndexRoute
  '/t/$tripId/admin/agent': typeof TTripIdAdminAgentRoute
  '/t/$tripId/admin/audit': typeof TTripIdAdminAuditRoute
  '/t/$tripId/admin/backups': typeof TTripIdAdminBackupsRoute
  '/t/$tripId/admin/itinerary': typeof TTripIdAdminItineraryRoute
  '/t/$tripId/admin/members': typeof TTripIdAdminMembersRoute
  '/t/$tripId/admin/settings': typeof TTripIdAdminSettingsRoute
  '/t/$tripId/admin/split': typeof TTripIdAdminSplitRoute
  '/t/$tripId/admin/suggestions': typeof TTripIdAdminSuggestionsRoute
  '/t/$tripId/admin': typeof TTripIdAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/ledger': typeof LedgerRoute
  '/timeline': typeof TimelineRoute
  '/admin/$': typeof AdminSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$tripId': typeof TTripIdRouteWithChildren
  '/t/$tripId/admin': typeof TTripIdAdminRouteWithChildren
  '/t/$tripId/bookings': typeof TTripIdBookingsRoute
  '/t/$tripId/ledger': typeof TTripIdLedgerRoute
  '/t/$tripId/timeline': typeof TTripIdTimelineRoute
  '/t/$tripId/': typeof TTripIdIndexRoute
  '/t/$tripId/admin/agent': typeof TTripIdAdminAgentRoute
  '/t/$tripId/admin/audit': typeof TTripIdAdminAuditRoute
  '/t/$tripId/admin/backups': typeof TTripIdAdminBackupsRoute
  '/t/$tripId/admin/itinerary': typeof TTripIdAdminItineraryRoute
  '/t/$tripId/admin/members': typeof TTripIdAdminMembersRoute
  '/t/$tripId/admin/settings': typeof TTripIdAdminSettingsRoute
  '/t/$tripId/admin/split': typeof TTripIdAdminSplitRoute
  '/t/$tripId/admin/suggestions': typeof TTripIdAdminSuggestionsRoute
  '/t/$tripId/admin/': typeof TTripIdAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/ledger'
    | '/timeline'
    | '/admin/$'
    | '/invite/$token'
    | '/t/$tripId'
    | '/t/$tripId/admin'
    | '/t/$tripId/bookings'
    | '/t/$tripId/ledger'
    | '/t/$tripId/timeline'
    | '/t/$tripId/'
    | '/t/$tripId/admin/agent'
    | '/t/$tripId/admin/audit'
    | '/t/$tripId/admin/backups'
    | '/t/$tripId/admin/itinerary'
    | '/t/$tripId/admin/members'
    | '/t/$tripId/admin/settings'
    | '/t/$tripId/admin/split'
    | '/t/$tripId/admin/suggestions'
    | '/t/$tripId/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/ledger'
    | '/timeline'
    | '/admin/$'
    | '/invite/$token'
    | '/t/$tripId/bookings'
    | '/t/$tripId/ledger'
    | '/t/$tripId/timeline'
    | '/t/$tripId'
    | '/t/$tripId/admin/agent'
    | '/t/$tripId/admin/audit'
    | '/t/$tripId/admin/backups'
    | '/t/$tripId/admin/itinerary'
    | '/t/$tripId/admin/members'
    | '/t/$tripId/admin/settings'
    | '/t/$tripId/admin/split'
    | '/t/$tripId/admin/suggestions'
    | '/t/$tripId/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/ledger'
    | '/timeline'
    | '/admin/$'
    | '/invite/$token'
    | '/t/$tripId'
    | '/t/$tripId/admin'
    | '/t/$tripId/bookings'
    | '/t/$tripId/ledger'
    | '/t/$tripId/timeline'
    | '/t/$tripId/'
    | '/t/$tripId/admin/agent'
    | '/t/$tripId/admin/audit'
    | '/t/$tripId/admin/backups'
    | '/t/$tripId/admin/itinerary'
    | '/t/$tripId/admin/members'
    | '/t/$tripId/admin/settings'
    | '/t/$tripId/admin/split'
    | '/t/$tripId/admin/suggestions'
    | '/t/$tripId/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  LedgerRoute: typeof LedgerRoute
  TimelineRoute: typeof TimelineRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TTripIdRoute: typeof TTripIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tripId': {
      id: '/t/$tripId'
      path: '/t/$tripId'
      fullPath: '/t/$tripId'
      preLoaderRoute: typeof TTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/t/$tripId/': {
      id: '/t/$tripId/'
      path: '/'
      fullPath: '/t/$tripId/'
      preLoaderRoute: typeof TTripIdIndexRouteImport
      parentRoute: typeof TTripIdRoute
    }
    '/t/$tripId/timeline': {
      id: '/t/$tripId/timeline'
      path: '/timeline'
      fullPath: '/t/$tripId/timeline'
      preLoaderRoute: typeof TTripIdTimelineRouteImport
      parentRoute: typeof TTripIdRoute
    }
    '/t/$tripId/ledger': {
      id: '/t/$tripId/ledger'
      path: '/ledger'
      fullPath: '/t/$tripId/ledger'
      preLoaderRoute: typeof TTripIdLedgerRouteImport
      parentRoute: typeof TTripIdRoute
    }
    '/t/$tripId/bookings': {
      id: '/t/$tripId/bookings'
      path: '/bookings'
      fullPath: '/t/$tripId/bookings'
      preLoaderRoute: typeof TTripIdBookingsRouteImport
      parentRoute: typeof TTripIdRoute
    }
    '/t/$tripId/admin': {
      id: '/t/$tripId/admin'
      path: '/admin'
      fullPath: '/t/$tripId/admin'
      preLoaderRoute: typeof TTripIdAdminRouteImport
      parentRoute: typeof TTripIdRoute
    }
    '/t/$tripId/admin/': {
      id: '/t/$tripId/admin/'
      path: '/'
      fullPath: '/t/$tripId/admin/'
      preLoaderRoute: typeof TTripIdAdminIndexRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/suggestions': {
      id: '/t/$tripId/admin/suggestions'
      path: '/suggestions'
      fullPath: '/t/$tripId/admin/suggestions'
      preLoaderRoute: typeof TTripIdAdminSuggestionsRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/split': {
      id: '/t/$tripId/admin/split'
      path: '/split'
      fullPath: '/t/$tripId/admin/split'
      preLoaderRoute: typeof TTripIdAdminSplitRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/settings': {
      id: '/t/$tripId/admin/settings'
      path: '/settings'
      fullPath: '/t/$tripId/admin/settings'
      preLoaderRoute: typeof TTripIdAdminSettingsRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/members': {
      id: '/t/$tripId/admin/members'
      path: '/members'
      fullPath: '/t/$tripId/admin/members'
      preLoaderRoute: typeof TTripIdAdminMembersRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/itinerary': {
      id: '/t/$tripId/admin/itinerary'
      path: '/itinerary'
      fullPath: '/t/$tripId/admin/itinerary'
      preLoaderRoute: typeof TTripIdAdminItineraryRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/backups': {
      id: '/t/$tripId/admin/backups'
      path: '/backups'
      fullPath: '/t/$tripId/admin/backups'
      preLoaderRoute: typeof TTripIdAdminBackupsRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/audit': {
      id: '/t/$tripId/admin/audit'
      path: '/audit'
      fullPath: '/t/$tripId/admin/audit'
      preLoaderRoute: typeof TTripIdAdminAuditRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
    '/t/$tripId/admin/agent': {
      id: '/t/$tripId/admin/agent'
      path: '/agent'
      fullPath: '/t/$tripId/admin/agent'
      preLoaderRoute: typeof TTripIdAdminAgentRouteImport
      parentRoute: typeof TTripIdAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TTripIdAdminRouteChildren {
  TTripIdAdminAgentRoute: typeof TTripIdAdminAgentRoute
  TTripIdAdminAuditRoute: typeof TTripIdAdminAuditRoute
  TTripIdAdminBackupsRoute: typeof TTripIdAdminBackupsRoute
  TTripIdAdminItineraryRoute: typeof TTripIdAdminItineraryRoute
  TTripIdAdminMembersRoute: typeof TTripIdAdminMembersRoute
  TTripIdAdminSettingsRoute: typeof TTripIdAdminSettingsRoute
  TTripIdAdminSplitRoute: typeof TTripIdAdminSplitRoute
  TTripIdAdminSuggestionsRoute: typeof TTripIdAdminSuggestionsRoute
  TTripIdAdminIndexRoute: typeof TTripIdAdminIndexRoute
}

const TTripIdAdminRouteChildren: TTripIdAdminRouteChildren = {
  TTripIdAdminAgentRoute: TTripIdAdminAgentRoute,
  TTripIdAdminAuditRoute: TTripIdAdminAuditRoute,
  TTripIdAdminBackupsRoute: TTripIdAdminBackupsRoute,
  TTripIdAdminItineraryRoute: TTripIdAdminItineraryRoute,
  TTripIdAdminMembersRoute: TTripIdAdminMembersRoute,
  TTripIdAdminSettingsRoute: TTripIdAdminSettingsRoute,
  TTripIdAdminSplitRoute: TTripIdAdminSplitRoute,
  TTripIdAdminSuggestionsRoute: TTripIdAdminSuggestionsRoute,
  TTripIdAdminIndexRoute: TTripIdAdminIndexRoute,
}

const TTripIdAdminRouteWithChildren = TTripIdAdminRoute._addFileChildren(
  TTripIdAdminRouteChildren,
)

interface TTripIdRouteChildren {
  TTripIdAdminRoute: typeof TTripIdAdminRouteWithChildren
  TTripIdBookingsRoute: typeof TTripIdBookingsRoute
  TTripIdLedgerRoute: typeof TTripIdLedgerRoute
  TTripIdTimelineRoute: typeof TTripIdTimelineRoute
  TTripIdIndexRoute: typeof TTripIdIndexRoute
}

const TTripIdRouteChildren: TTripIdRouteChildren = {
  TTripIdAdminRoute: TTripIdAdminRouteWithChildren,
  TTripIdBookingsRoute: TTripIdBookingsRoute,
  TTripIdLedgerRoute: TTripIdLedgerRoute,
  TTripIdTimelineRoute: TTripIdTimelineRoute,
  TTripIdIndexRoute: TTripIdIndexRoute,
}

const TTripIdRouteWithChildren =
  TTripIdRoute._addFileChildren(TTripIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  LedgerRoute: LedgerRoute,
  TimelineRoute: TimelineRoute,
  InviteTokenRoute: InviteTokenRoute,
  TTripIdRoute: TTripIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
